In [41]:
import pandas as pd

df_Combined_BOB = pd.read_csv('cleaned_BOB_df.csv')
cleaned_Outliers_df = pd.read_csv('cleaned_Outliers.csv')

print(df_Combined_BOB.info())
print(cleaned_Outliers_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Nombre del huésped    32 non-null     object
 1   Contacto              8 non-null      object
 2   Número de adultos     32 non-null     int64
 3   Número de niños       32 non-null     int64
 4   Ingreso               32 non-null     object
 5   Salida                32 non-null     object
 6   Número de noches      32 non-null     int64
 7   Fecha de Reservación  0 non-null      float64
 8   Propietario           32 non-null     object
 9   Propiedad             32 non-null     object
 10  Ingresos Totales BOB  32 non-null     float64
 11  Limpieza BOB          32 non-null     float64
 12  Property Type         32 non-null     object
 13  Management            32 non-null     object
dtypes: float64(3), int64(3), object(8)
memory usage: 3.6+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Código de confirmación  232 non-null    object
 1   Estado                  232 non-null    object
 2   Nombre del huésped      232 non-null    object
 3   Contacto                27 non-null     object
 4   Número de adultos       232 non-null    int64
 5   Número de niños         232 non-null    int64
 6   Número de bebés         232 non-null    int64
 7   Ingreso                 232 non-null    object
 8   Salida                  232 non-null    object
 9   Número de noches        232 non-null    int64
 10  Fecha de Reservación    232 non-null    object
 11  Propiedad               232 non-null    object
 12  Ingresos Totales        232 non-null    float64
 13  Property Type           232 non-null    object
 14  Management              232 non-null    object
 15  Propietario             232 non-null    object
dtypes: float64(1), int64(4), object(11)
memory usage: 29.1+ KB
None

In [42]:
# Crear Código de confirmación artificial en df_combined_BOB
df_combined_BOB = df_Combined_BOB.copy()
df_combined_BOB["Código de confirmación"] = ["COH{:05d}".format(i) for i in range(1, len(df_combined_BOB) + 1)]

# Definir columnas comunes deseadas (sin columnas de dinero)
columns_to_keep = [
    "Código de confirmación", "Nombre del huésped", "Contacto", "Número de adultos",
    "Número de niños", "Ingreso", "Salida", "Número de noches", "Fecha de Reservación",
    "Propiedad", "Property Type", "Management", "Propietario"
]

# Seleccionar columnas deseadas en ambos DFs
df_BOB_clean = df_combined_BOB[columns_to_keep]
df_USD_clean = cleaned_Outliers_df[columns_to_keep]

# 4. Concatenar
df_analysis = pd.concat([df_BOB_clean, df_USD_clean], ignore_index=True)

print(df_analysis.info())
print(df_analysis[['Ingreso', 'Salida', 'Fecha de Reservación']])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Código de confirmación  264 non-null    object
 1   Nombre del huésped      264 non-null    object
 2   Contacto                35 non-null     object
 3   Número de adultos       264 non-null    int64
 4   Número de niños         264 non-null    int64
 5   Ingreso                 264 non-null    object
 6   Salida                  264 non-null    object
 7   Número de noches        264 non-null    int64
 8   Fecha de Reservación    232 non-null    object
 9   Propiedad               264 non-null    object
 10  Property Type           264 non-null    object
 11  Management              264 non-null    object
 12  Propietario             264 non-null    object
dtypes: int64(3), object(10)
memory usage: 26.9+ KB
None
        Ingreso      Salida Fecha de Reservación
0    2025-02-27  2025-03-01                  NaN
1    2025-03-08  2025-03-10                  NaN
2    2025-02-16  2025-02-21                  NaN
3    2025-02-28  2025-03-01                  NaN
4    2025-02-26  2025-02-28                  NaN
..          ...         ...                  ...
259  2025-02-16  2025-03-02           2025-02-15
260  2025-02-24  2025-02-27           2025-02-24
261  2025-02-13  2025-02-20           2024-12-09
262  2025-02-15  2025-02-16           2025-01-30
263  2025-02-14  2025-02-15           2025-02-14

[264 rows x 3 columns]

In [43]:
# Convirtiendo la columna Ingreso de object a date
# Create a copy of df_analysis to avoid modifying the original dataframe
cleaned_df_analysis = df_analysis.copy()

# Limpiar espacios en blanco y forzar string
cleaned_df_analysis['Ingreso'] = cleaned_df_analysis['Ingreso'].astype(str).str.strip()

cleaned_df_analysis['Ingreso'] = pd.to_datetime(cleaned_df_analysis['Ingreso'], errors='coerce')

# Verificar si hay valores nulos después de la conversión
if cleaned_df_analysis['Ingreso'].isna().any():
    print("Existen valores no convertidos a datetime. Revisa los siguientes datos:")
    print(cleaned_df_analysis[cleaned_df_analysis['Ingreso'].isna()])

# Mostrar el tipo de la columna después de la conversión
print(cleaned_df_analysis['Ingreso'].dtype)
print(cleaned_df_analysis.info())

datetime64[ns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Código de confirmación  264 non-null    object
 1   Nombre del huésped      264 non-null    object
 2   Contacto                35 non-null     object
 3   Número de adultos       264 non-null    int64
 4   Número de niños         264 non-null    int64
 5   Ingreso                 264 non-null    datetime64[ns]
 6   Salida                  264 non-null    object
 7   Número de noches        264 non-null    int64
 8   Fecha de Reservación    232 non-null    object
 9   Propiedad               264 non-null    object
 10  Property Type           264 non-null    object
 11  Management              264 non-null    object
 12  Propietario             264 non-null    object
dtypes: datetime64[ns](1), int64(3), object(9)
memory usage: 26.9+ KB
None

In [44]:
# Convirtiendo la columna Salida de object a date en cleaned_df_analysis

# Limpiar espacios en blanco y forzar string
cleaned_df_analysis['Salida'] = cleaned_df_analysis['Salida'].astype(str).str.strip()

cleaned_df_analysis['Salida'] = pd.to_datetime(cleaned_df_analysis['Salida'], errors='coerce')

# Verificar si hay valores nulos después de la conversión
if cleaned_df_analysis['Salida'].isna().any():
    print("Existen valores no convertidos a datetime. Revisa los siguientes datos:")
    print(cleaned_df_analysis[cleaned_df_analysis['Salida'].isna()])

# Mostrar el tipo de la columna después de la conversión
print(cleaned_df_analysis['Salida'].dtype)
print(cleaned_df_analysis.info())

datetime64[ns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Código de confirmación  264 non-null    object
 1   Nombre del huésped      264 non-null    object
 2   Contacto                35 non-null     object
 3   Número de adultos       264 non-null    int64
 4   Número de niños         264 non-null    int64
 5   Ingreso                 264 non-null    datetime64[ns]
 6   Salida                  264 non-null    datetime64[ns]
 7   Número de noches        264 non-null    int64
 8   Fecha de Reservación    232 non-null    object
 9   Propiedad               264 non-null    object
 10  Property Type           264 non-null    object
 11  Management              264 non-null    object
 12  Propietario             264 non-null    object
dtypes: datetime64[ns](2), int64(3), object(8)
memory usage: 26.9+ KB
None

In [45]:
# Convirtiendo la columna Fecha de Reservación de object a date en cleaned_df_analysis

# Si en el formulario de Excel se deja vacio la casilla de Fecha de Reservación, esta se guarda como "00/01/1900" en la BBDD
# Convertir a string y limpiar espacios
cleaned_df_analysis["Fecha de Reservación"] = cleaned_df_analysis["Fecha de Reservación"].astype(str).str.strip()

cleaned_df_analysis['Fecha de Reservación'] = pd.to_datetime(cleaned_df_analysis['Fecha de Reservación'], errors='coerce')

# Verify if there are NaT values after conversion, many values will come as NaT values from the excel form.
if cleaned_df_analysis['Fecha de Reservación'].isna().any():
    print("Existen valores no convertidos a datetime. Revisa los siguientes datos:")
    print(cleaned_df_analysis[cleaned_df_analysis['Fecha de Reservación'].isna()])

# Display the column type after conversion
print(cleaned_df_analysis['Fecha de Reservación'].dtype)
print(cleaned_df_analysis.info())

Existen valores no convertidos a datetime. Revisa los siguientes datos:
   Código de confirmación                     Nombre del huésped  \
0                COH00001                   Gustavo Rodolfo Vega
1                COH00002               Jose Antonio Rivero Moro
2                COH00003        Luis Alexander Espinoza La Cruz
3                COH00004                          Erick Herrera
4                COH00005                          Erick Herrera
5                COH00006       Antonio Alexandre Consoni Vigano
6                COH00007                          Pablo Montaño
7                COH00008                   Richard Leon Condori
8                COH00009                     Yudy Kahuana Soliz
9                COH00010                         Ricardo Ortega
10               COH00011          Mario Andres Torrico Bautista
11               COH00012                 Bladimir Muriel Mamani
12               COH00013           Elba Maria Bolanos del Prado
13               COH00014             Marco Antonio Lopez Zurita
14               COH00015          Guillermo Alejandro Rodriguez
15               COH00016                         Jose Valasquez
16               COH00017                Hilda Georgina Terrazas
17               COH00018                  Jaime Candido Machado
18               COH00019                     Jaime Diaz Garnica
19               COH00020                     Yudy Kahuana Soliz
20               COH00021                         Ricardo Ortega
21               COH00022          Mario Andres Torrico Bautista
22               COH00023                    Hugo Andres Pizarro
23               COH00024                    Efrain Cuiza Quispa
24               COH00025                  Juan Carlos Dominguez
25               COH00026  Karin Sauma Navajasvivian Salvatierra
26               COH00027                        Daniel Illescas
27               COH00028                       Renato Rodrigues
28               COH00029                 Bladimir Muriel Mamani
29               COH00030                 Alberto Cuellar Rivero
30               COH00031                     Juan Carlos Mamani
31               COH00032         Giovanna Judith Martinez Bravo

         Contacto  Número de adultos  Número de niños    Ingreso     Salida  \
0             NaN                  1                0 2025-02-27 2025-03-01
1             NaN                  2                0 2025-03-08 2025-03-10
2             NaN                  1                0 2025-02-16 2025-02-21
3   +591 78434480                  1                0 2025-02-28 2025-03-01
4   +591 78434480                  1                0 2025-02-26 2025-02-28
5             NaN                  2                0 2025-02-14 2025-02-17
6             NaN                  4                0 2025-01-21 2025-01-22
7             NaN                  4                0 2025-01-18 2025-01-21
8             NaN                  2                0 2025-01-17 2025-01-18
9             NaN                  4                0 2025-01-12 2025-01-17
10            NaN                  2                0 2025-01-11 2025-01-12
11            NaN                  2                0 2025-02-15 2025-02-20
12            NaN                  2                0 2025-02-14 2025-02-15
13            NaN                  2                0 2025-01-24 2025-01-26
14            NaN                  1                0 2025-02-27 2025-02-28
15            NaN                  2                0 2025-02-08 2025-02-09
16            NaN                  2                0 2025-02-02 2025-03-02
17            NaN                  2                0 2025-01-27 2025-02-27
18            NaN                  2                0 2025-01-25 2025-01-27
19            NaN                  4                0 2025-01-17 2025-01-18
20            NaN                  4                0 2025-01-12 2025-01-17
21            NaN                  2                0 2025-01-11 2025-01-12
22            NaN                  2                0 2025-01-18 2025-01-19
23            NaN                  3                0 2025-01-16 2025-01-18
24            NaN                  3                0 2025-01-21 2025-01-24
25            NaN                  2                0 2025-01-17 2025-01-19
26  +591 67985704                  2                0 2025-02-27 2025-03-16
27              0                  3                0 2025-01-28 2025-01-02
28              0                  1                0 2025-01-02 2025-02-02
29              0                  1                0 2025-01-29 2025-01-31
30              0                  4                0 2025-01-18 2025-01-20
31              0                  2                0 2025-01-16 2025-01-17

    Número de noches Fecha de Reservación          Propiedad  Property Type  \
0                  2                  NaT    SKY ELITE - 320   Monoambiente
1                  2                  NaT    SKY ELITE - 524   Monoambiente
2                  5                  NaT    SKY ELITE - 524   Monoambiente
3                  1                  NaT    SKY ELITE - 115   Monoambiente
4                  2                  NaT    SKY ELITE - 115   Monoambiente
5                  3                  NaT    SKY ELITE - 115   Monoambiente
6                  1                  NaT    SKY ELITE - 132   1 Dormitorio
7                  3                  NaT    SKY ELITE - 132   1 Dormitorio
8                  1                  NaT    SKY ELITE - 132   1 Dormitorio
9                  5                  NaT    SKY ELITE - 132   1 Dormitorio
10                 1                  NaT    SKY ELITE - 132   1 Dormitorio
11                 6                  NaT    SKY LUXIA - 513   Monoambiente
12                 1                  NaT    SKY LUXIA - 513   Monoambiente
13                 3                  NaT    SKY ELITE - 115   Monoambiente
14                 1                  NaT    SKY ELITE - 524   Monoambiente
15                 1                  NaT    SKY ELITE - 524   Monoambiente
16                 1                  NaT    SKY ELITE - 524   Monoambiente
17                31                  NaT    SKY ELITE - 320   Monoambiente
18                 2                  NaT    SKY ELITE - 320   Monoambiente
19                 1                  NaT    SKY ELITE - 132   1 Dormitorio
20                 5                  NaT    SKY ELITE - 132   1 Dormitorio
21                 1                  NaT    SKY ELITE - 132   1 Dormitorio
22                 1                  NaT    SKY ELITE - 524   Monoambiente
23                 2                  NaT    SKY ELITE - 524   Monoambiente
24                 3                  NaT    SKY ELITE - 320   Monoambiente
25                 2                  NaT    SKY ELITE - 320   Monoambiente
26                17                  NaT  MACORORO 12 - 12F   1 Dormitorio
27                 4                  NaT   MACORORO 15 - 8G  3 Dormitorios
28                 1                  NaT    SKY ELITE - 229   Monoambiente
29                 2                  NaT    SKY ELITE - 229   Monoambiente
30                 2                  NaT    SKY ELITE - 229   Monoambiente
31                 1                  NaT    SKY ELITE - 229   Monoambiente

      Management        Propietario
0   Administrada          Dr. Ortiz
1   Administrada          Dr. Ortiz
2   Administrada          Dr. Ortiz
3   Administrada       Boris Ayviri
4   Administrada       Boris Ayviri
5   Administrada       Boris Ayviri
6   Administrada  Lic. Freddy Soria
7   Administrada  Lic. Freddy Soria
8   Administrada  Lic. Freddy Soria
9   Administrada  Lic. Freddy Soria
10  Administrada  Lic. Freddy Soria
11  Administrada          Dr. Ortiz
12  Administrada          Dr. Ortiz
13  Administrada       Boris Ayviri
14  Administrada          Dr. Ortiz
15  Administrada          Dr. Ortiz
16  Administrada          Dr. Ortiz
17  Administrada          Dr. Ortiz
18  Administrada          Dr. Ortiz
19  Administrada  Lic. Freddy Soria
20  Administrada  Lic. Freddy Soria
21  Administrada  Lic. Freddy Soria
22  Administrada          Dr. Ortiz
23  Administrada          Dr. Ortiz
24  Administrada          Dr. Ortiz
25  Administrada          Dr. Ortiz
26        Propia            Familia
27        Propia            Familia
28        Propia            Familia
29        Propia            Familia
30        Propia            Familia
31        Propia            Familia
datetime64[ns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Código de confirmación  264 non-null    object
 1   Nombre del huésped      264 non-null    object
 2   Contacto                35 non-null     object
 3   Número de adultos       264 non-null    int64
 4   Número de niños         264 non-null    int64
 5   Ingreso                 264 non-null    datetime64[ns]
 6   Salida                  264 non-null    datetime64[ns]
 7   Número de noches        264 non-null    int64
 8   Fecha de Reservación    232 non-null    datetime64[ns]
 9   Propiedad               264 non-null    object
 10  Property Type           264 non-null    object
 11  Management              264 non-null    object
 12  Propietario             264 non-null    object
dtypes: datetime64[ns](3), int64(3), object(7)
memory usage: 26.9+ KB
None

In [46]:
# For global Analysis
print(cleaned_df_analysis.info())

# Night's book DataFrame, to see the Ocupancy rate per property and the average # of Nights per property. We'll also see average
# Booking Lead Time per property
ocupancy_property_df = cleaned_df_analysis[['Ingreso', 'Salida', 'Número de noches', 'Fecha de Reservación', 'Propiedad', 'Property Type']].copy()

# Agregar Mes y Año
ocupancy_property_df["Month"] = ocupancy_property_df["Ingreso"].dt.month
ocupancy_property_df["Year"] = ocupancy_property_df["Ingreso"].dt.year

# Calculate Booking Lead Time (Days Between Booking and Check-In)
ocupancy_property_df["Lead Time"] = (ocupancy_property_df["Ingreso"] - ocupancy_property_df["Fecha de Reservación"]).dt.days
#print(ocupancy_property_df.head())

# ------------------ OCCUPANCY RATE AND BOOKING LEAD TIME FOR PROPERTY ------------------
# Aggregate Nights Booked per Property, Month, Year
occupancy_prop_df = ocupancy_property_df.groupby(["Propiedad", "Month", "Year"]).agg({
    "Número de noches": "sum",
    "Lead Time": "mean"}).reset_index()
occupancy_prop_df.rename(columns={"Número de noches": "Total Nights Booked per Property", "Lead Time": "Avg Lead Time per Property"}, inplace=True)

# Calculate Total Available Nights Based on Month
import calendar
occupancy_prop_df["Total Available Nights"] = occupancy_prop_df["Month"].apply(lambda x: calendar.monthrange(2024, x)[1])

# Calculate Occupancy Rate for Each Property
occupancy_prop_df["Occupancy Rate (%)"] = (occupancy_prop_df["Total Nights Booked per Property"] / occupancy_prop_df["Total Available Nights"]) * 100
print(occupancy_prop_df.head())

# ------------------ OCCUPANCY RATE FOR PROPERTY TYPE ------------------
occupancy_type_df = ocupancy_property_df.groupby(["Property Type", "Month", "Year"]).agg({
    "Número de noches": "sum",
    "Lead Time": "mean"}).reset_index()
occupancy_type_df.rename(columns={"Número de noches": "Total Nights Booked per Property Type", "Lead Time": "Avg Lead Time per Property Type"}, inplace=True)

# Calculate Total Available Nights Based on Month
occupancy_type_df["Total Available Nights"] = occupancy_type_df["Month"].apply(lambda x: calendar.monthrange(2024, x)[1])

# Calculate Occupancy Rate for Each Property Type
occupancy_type_df["Occupancy Rate (%)"] = (occupancy_type_df["Total Nights Booked per Property Type"] / occupancy_type_df["Total Available Nights"]) * 100
print(occupancy_type_df.head())


# One will be used for day to day transactions, such as occupancy rate. Used for: Occupancy rates, Booking lead time, Lenght Stay trends, Loyalty trends
# The other will be used for aggregated functions for property comparisons, between months. Used for: Earnings analysis, Demographic Analysis, Seasonal Analysis

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Código de confirmación  264 non-null    object
 1   Nombre del huésped      264 non-null    object
 2   Contacto                35 non-null     object
 3   Número de adultos       264 non-null    int64
 4   Número de niños         264 non-null    int64
 5   Ingreso                 264 non-null    datetime64[ns]
 6   Salida                  264 non-null    datetime64[ns]
 7   Número de noches        264 non-null    int64
 8   Fecha de Reservación    232 non-null    datetime64[ns]
 9   Propiedad               264 non-null    object
 10  Property Type           264 non-null    object
 11  Management              264 non-null    object
 12  Propietario             264 non-null    object
dtypes: datetime64[ns](3), int64(3), object(7)
memory usage: 26.9+ KB
None
                       Propiedad  Month  Year  \
0  HOTEL RADISSON - SENIOR SUITE      1  2024
1  HOTEL RADISSON - SENIOR SUITE      2  2024
2  HOTEL RADISSON - SENIOR SUITE      7  2024
3  HOTEL RADISSON - SENIOR SUITE      8  2024
4              MACORORO 12 - 12F      1  2025

   Total Nights Booked per Property  Avg Lead Time per Property  \
0                                 1                         0.0
1                                 3                        29.0
2                                 3                         1.0
3                                 6                         6.5
4                                16                         7.0

   Total Available Nights  Occupancy Rate (%)
0                      31            3.225806
1                      29           10.344828
2                      31            9.677419
3                      31           19.354839
4                      31           51.612903
  Property Type  Month  Year  Total Nights Booked per Property Type  \
0  1 Dormitorio      1  2023                                      2
1  1 Dormitorio      1  2024                                     13
2  1 Dormitorio      1  2025                                     34
3  1 Dormitorio      2  2022                                      8
4  1 Dormitorio      2  2023                                      3

   Avg Lead Time per Property Type  Total Available Nights  Occupancy Rate (%)
0                         0.000000                      31            6.451613
1                         0.666667                      31           41.935484
2                         7.000000                      31          109.677419
3                         1.000000                      29           27.586207
4                         3.000000                      29           10.344828

In [47]:
# There was an interpretation mistake done while making the occupancy rate analysis.
# There are months were there were no bookings, are this months are actually not shown in the current dataframe.
# All months must appear and if no bookings are registered, there should be a 0% occupancy rate
# Months should start count from the first month the first property was offered, in the "Ingreso" column

from datetime import datetime

# Get current year and month (real-time reference)
current_year = datetime.today().year
current_month = datetime.today().month

# Get the first 'Ingreso' (first booking date) for each property
first_offer_date = ocupancy_property_df.groupby("Propiedad")["Ingreso"].min().reset_index()
first_offer_date.rename(columns={"Ingreso": "First Ingreso"}, inplace=True)

first_offer_date["First Year"] = first_offer_date["First Ingreso"].dt.year
first_offer_date["First Month"] = first_offer_date["First Ingreso"].dt.month

# Get the full date range from the first to the last 'Ingreso'
min_year, min_month = ocupancy_property_df["Ingreso"].min().year, ocupancy_property_df["Ingreso"].min().month

from itertools import product

# Create a full list of month-year combinations
all_months_years = pd.DataFrame(
    list(product(range(min_year, current_year + 1), range(1, 13))),
    columns=["Year", "Month"]
)

# Filter to ensure we don't include months beyond the current real-time month
all_months_years = all_months_years[
    (all_months_years["Year"] < current_year) | 
    ((all_months_years["Year"] == current_year) & (all_months_years["Month"] <= current_month))
]

# ------------------ COMPLETE OCCUPANCY DATA PER PROPERTY ------------------

# Get all unique properties
all_properties = ocupancy_property_df[['Propiedad']].drop_duplicates()

# Cross join properties with all months/years
full_prop_df = all_properties.merge(all_months_years, how="cross")

# Merge to get the first offer date per property
full_prop_df = full_prop_df.merge(first_offer_date, on="Propiedad", how="left")

# Filter out months before the property was offered
full_prop_df = full_prop_df[
    (full_prop_df["Year"] > full_prop_df["First Year"]) | 
    ((full_prop_df["Year"] == full_prop_df["First Year"]) & (full_prop_df["Month"] >= full_prop_df["First Month"]))
]

# Drop unnecessary columns
full_prop_df2 = full_prop_df.drop(columns=["First Ingreso", "First Year", "First Month"]).copy()

# Merge with existing occupancy data into a new DataFrame
occupancy_prop_df2 = full_prop_df2.merge(occupancy_prop_df, on=["Propiedad", "Year", "Month"], how="left")

# Fill missing values with 0 for occupancy-related metrics
occupancy_prop_df2["Total Nights Booked per Property"] = occupancy_prop_df2["Total Nights Booked per Property"].fillna(0)
occupancy_prop_df2["Total Available Nights"] = occupancy_prop_df2["Month"].apply(lambda x: calendar.monthrange(2024, x)[1])
occupancy_prop_df2["Occupancy Rate (%)"] = (occupancy_prop_df2["Total Nights Booked per Property"] / occupancy_prop_df2["Total Available Nights"]) * 100

print(occupancy_prop_df2.head())

         Propiedad  Year  Month  Total Nights Booked per Property  \
0  SKY ELITE - 320  2023     12                              13.0
1  SKY ELITE - 320  2024      1                               3.0
2  SKY ELITE - 320  2024      2                               9.0
3  SKY ELITE - 320  2024      3                              11.0
4  SKY ELITE - 320  2024      4                               6.0

   Avg Lead Time per Property  Total Available Nights  Occupancy Rate (%)
0                    3.666667                      31           41.935484
1                    3.000000                      31            9.677419
2                   14.500000                      29           31.034483
3                    0.800000                      31           35.483871
4                   21.666667                      30           20.000000

In [48]:
# We continue with the occupancy_type_df, where apart from the mistake made with occupancy_prop_df, there were also months
# were the occupancy rate was more than 100%, this is due because there might be more than 1 porperty as a property type,
# meaning that when we sum up the booked nights, we might get more than the total aviable nights. Total aviable nights should be
# dynamic, depending on the number of properties in a property type and month


# ------------------ COMPLETE OCCUPANCY DATA PER PROPERTY TYPE ------------------

# Map each property to its property type
property_type_mapping = ocupancy_property_df[['Propiedad', 'Property Type']].drop_duplicates()

# Merge to get the first booking date per property type
property_first_booking = first_offer_date.merge(property_type_mapping, on="Propiedad", how="left")

# Get first offer date per property type (Earliest Date for each Property Type)
property_first_booking = property_first_booking.groupby("Property Type")["First Ingreso"].min().reset_index()
property_first_booking["First Year"] = property_first_booking["First Ingreso"].dt.year
property_first_booking["First Month"] = property_first_booking["First Ingreso"].dt.month

# Get all unique property types
all_property_types = ocupancy_property_df[['Property Type']].drop_duplicates()

# Cross join property types with all months/years (Reuse 'all_months_years')
full_type_df = all_property_types.merge(all_months_years, how="cross")

# Merge with the first available booking date per property type
full_type_df = full_type_df.merge(property_first_booking, on="Property Type", how="left")


# FILTER OUT MONTHS BEFORE THE FIRST TIME A PROPERTY TYPE WAS OFFERED
full_type_df = full_type_df[
    (full_type_df["Year"] > full_type_df["First Year"]) | 
    ((full_type_df["Year"] == full_type_df["First Year"]) & (full_type_df["Month"] >= full_type_df["First Month"]))
]

# Drop unnecessary columns
full_type_df = full_type_df.drop(columns=["First Ingreso", "First Year", "First Month"]).copy()

# Count available properties per type each month (Reuse 'ocupancy_property_df')
available_properties_per_month = ocupancy_property_df.groupby(["Property Type", "Year", "Month"])["Propiedad"].nunique().reset_index()
available_properties_per_month.rename(columns={"Propiedad": "Available Properties"}, inplace=True)

# Merge to get the number of properties available each month per type
full_type_df = full_type_df.merge(available_properties_per_month, on=["Property Type", "Year", "Month"], how="left")

# Fill NaN values (months with 0 properties should be counted as 0)
full_type_df["Available Properties"] = full_type_df["Available Properties"].fillna(0)

# Merge with existing occupancy data (Reuse 'occupancy_type_df')
occupancy_type_df2 = full_type_df.merge(occupancy_type_df, on=["Property Type", "Year", "Month"], how="left")

# Fill missing values with 0 for total nights booked
occupancy_type_df2["Total Nights Booked per Property Type"] = occupancy_type_df2["Total Nights Booked per Property Type"].fillna(0)

# Ensure available nights are calculated correctly even if there are no bookings
occupancy_type_df2["Total Available Nights"] = occupancy_type_df2.apply(
    lambda row: max(row["Available Properties"], 1) * calendar.monthrange(row["Year"], row["Month"])[1], axis=1
)

# Compute Corrected Occupancy Rate
occupancy_type_df2["Occupancy Rate (%)"] = (
    occupancy_type_df2["Total Nights Booked per Property Type"] / occupancy_type_df2["Total Available Nights"]
) * 100

# Ensure no occupancy rate exceeds 100%
occupancy_type_df2["Occupancy Rate (%)"] = occupancy_type_df2["Occupancy Rate (%)"].clip(upper=100)

print(occupancy_type_df2.head())

  Property Type  Year  Month  Available Properties  \
0  Monoambiente  2023     12                   3.0
1  Monoambiente  2024      1                   3.0
2  Monoambiente  2024      2                   3.0
3  Monoambiente  2024      3                   3.0
4  Monoambiente  2024      4                   3.0

   Total Nights Booked per Property Type  Avg Lead Time per Property Type  \
0                                   50.0                         4.272727
1                                   23.0                         1.625000
2                                   20.0                        23.600000
3                                   19.0                         3.800000
4                                   40.0                         9.250000

   Total Available Nights  Occupancy Rate (%)
0                    93.0           53.763441
1                    93.0           24.731183
2                    87.0           22.988506
3                    93.0           20.430108
4                    90.0           44.444444

In [49]:
# Customer Analysis
# I'll be creating a customer_loyalty_df to see which customers re used our services, percent of customers that only used once our 
# services, and percent of customers that used more than once our services. Demography of our clients

customer_df = cleaned_df_analysis[['Código de confirmación', 'Nombre del huésped', 'Contacto', 'Número de adultos', 'Número de niños', 'Propiedad', 'Property Type']].copy()

# Crear un identificador único por huésped (puede ser nombre o contacto si falta el nombre)
customer_df["Guest Identifier"] = customer_df.apply(lambda x: x["Nombre del huésped"] if pd.notna(x["Nombre del huésped"]) else x["Contacto"], axis=1)

# Agrupar por huésped y contar la cantidad de reservas (Total Bookings)
customer_loyalty_df = customer_df.groupby("Guest Identifier").agg({"Código de confirmación": "nunique"}).reset_index()

# Renombrar columnas
customer_loyalty_df.rename(columns={"Código de confirmación": "Total Bookings"}, inplace=True)
customer_loyalty_df = customer_loyalty_df.sort_values(by="Total Bookings", ascending=False)
print(customer_loyalty_df.head())
print(customer_loyalty_df.info())
print(customer_loyalty_df.describe())

           Guest Identifier  Total Bookings
104  Jorge Augusto Sobreira              24
80        Hernan Justiniano               5
123               Ling Chen               4
110    José Carlos Orellana               3
205  Yomi Chavez Casablanca               3
<class 'pandas.core.frame.DataFrame'>
Index: 208 entries, 104 to 207
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Guest Identifier  208 non-null    object
 1   Total Bookings    208 non-null    int64
dtypes: int64(1), object(1)
memory usage: 4.9+ KB
None
       Total Bookings
count      208.000000
mean         1.269231
std          1.657836
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         24.000000

In [50]:
# Customer Demographic

# ------------------ CUSTOMER DEMOGRAPHICS PER PROPERTY ------------------
customer_demograph_property_df = customer_df.groupby(["Propiedad"]).agg({
    "Número de adultos": "sum",
    "Número de niños": "sum",
    "Código de confirmación": "count"  # Total bookings per property
}).reset_index()

customer_demograph_property_df.rename(columns={"Confirmation Code": "Total Bookings"}, inplace=True)
print(customer_demograph_property_df)

# ------------------ CUSTOMER DEMOGRAPHICS PER PROPERTY TYPE ------------------
customer_demograph_type_df = customer_df.groupby(["Property Type"]).agg({
    "Número de adultos": "sum",
    "Número de niños": "sum",
    "Código de confirmación": "count"
}).reset_index()

customer_demograph_type_df.rename(columns={"Confirmation Code": "Total Bookings"}, inplace=True)
print(customer_demograph_type_df)

                        Propiedad  Número de adultos  Número de niños  \
0   HOTEL RADISSON - SENIOR SUITE                  9                0
1               MACORORO 12 - 12F                 74                1
2                MACORORO 15 - 8G                 39                4
3                      MACORORO 8                 23                0
4                 SKY ELITE - 115                 20                0
5                 SKY ELITE - 132                 45                0
6                 SKY ELITE - 229                 57                0
7                 SKY ELITE - 320                 68                3
8                 SKY ELITE - 323                 39                2
9                 SKY ELITE - 510                 13                0
10                SKY ELITE - 524                 47                4
11                SKY LUXIA - 513                  6                0
12             TORRES SIRARI - 5A                 27                1
13                      YOU - 316                 19                0

    Código de confirmación
0                        5
1                       42
2                       12
3                       14
4                       12
5                       18
6                       37
7                       43
8                       18
9                        9
10                      26
11                       3
12                      12
13                      13
   Property Type  Número de adultos  Número de niños  Código de confirmación
0   1 Dormitorio                169                2                      86
1  3 Dormitorios                 39                4                      12
2   Monoambiente                269                9                     161
3   Senior Suite                  9                0                       5

In [51]:
# Exporting tables to csv

# cleaned_DateTime_df will be used as an Earning Analysis table
# cleaned_DateTime_df.to_csv("cleaned_DataFrame.csv", index=False)
# cleaned_Outliers_df will be used for statistics that can be influenced from a skewed distributions such as mean
# cleaned_Outliers_df.to_csv("cleaned_Outliers.csv", index=False)
# occupancy_prop_df will be used for occupancy rate and leading time analysis
occupancy_prop_df.to_csv("occupancy_leading_by_property.csv", index=False)
# occupancy_type_df will be used for occupancy rate and leading time analysis
occupancy_type_df.to_csv("occupancy_leading_by_property_type.csv", index=False)
# customer_loyalty_df will be used to answer, are our services re used, or just used once?
customer_loyalty_df.to_csv("customer_loyalty_demographics.csv", index=False)
# customer_demograph_property_df circle graph to see demography in properties
customer_demograph_property_df.to_csv("customer_demographics_by_property.csv", index=False)
# customer_demograph_type_df circle graph to see demography in property types
customer_demograph_type_df.to_csv("customer_demographics_by_property_type.csv", index=False)
# occupancy_prop_df2 will be used for occupancy rate, this is the offical version
occupancy_prop_df2.to_csv("occupancy_by_property.csv", index=False)
# occupancy_type_df2 will be used for occupancy rate, this is the official version
occupancy_type_df2.to_csv("occupancy_by_type.csv", index=False)